epochs: 100
total_samples: 20
concurrent_trials: 3
data_dir: "/data/malio/softsys/imgs_data"
image_size: [4800, 660] #[H,W]
wandb_project_name: "SoftSystem_Image_Grid_Search"
run_name: "cnn_contrastive"

dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  sobel: false

param_grid:
  model:
    tune_type: choice
    # values: ['cnn', 'vit']
    values: ['cnn']
  learning_rate:
    tune_type: choice
    values: [0.001, 0.0001]
  batch_size:
    tune_type: choice
    values: [4, 8]
  use_contrastive:
    tune_type: choice
    values: [true]
  model_depth:
    tune_type: choice
    values: [2, 3]
  kernel_size:
    tune_type: choice
    values: [3, 5]
  latent_dim:
    tune_type: choice
    values: [16, 32, 64]
  stride:
    tune_type: choice
    values: [1]
  padding:
    tune_type: choice
    values: ['same']
