epochs: 100
total_samples: 10
concurrent_trials: 1
data_dir: "/data/malio/softsys/imgs_data"
image_size: [660, 4800]
wandb_project_name: "SoftSystem_Image_Grid_Search"

param_grid:
  model:
    tune_type: choice
    values: ['cnn', 'vit']
  learning_rate:
    tune_type: choice
    values: [0.001, 0.0001]
  batch_size:
    tune_type: choice
    values: [4, 8]
  model_depth:
    tune_type: choice
    values: [2, 3]
  kernel_size:
    tune_type: choice
    values: [3, 5]
  latent_dim:
    tune_type: choice
    values: [16, 32, 64]
  stride:
    tune_type: choice
    values: [1]
  padding:
    tune_type: choice
    values: ['same']
