epochs: 100
total_samples: 1
concurrent_trials: 1
data_dir: "/data/malio/softsys/imgs_data"
# image_size: [4800, 660] #[H,W]
pooling_size: [32, 32]  #[H,W]
wandb_project_name: "SoftSystem_Image_Grid_Search"
run_name: "cnn_contrastive"

dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  sobel: false

param_grid:
  model:
    tune_type: choice
    # values: ['cnn', 'vit']
    values: ['cnn']
  learning_rate:
    tune_type: uniform
    min: 0.0001
    max: 0.001
  batch_size:
    tune_type: choice
    values: [4, 8]
  use_contrastive:
    tune_type: choice
    values: [true]
  supcon_weight:
      tune_type: uniform
      min: 0.2
      max: 0.8
  model_depth:
    tune_type: choice
    values: [2, 3]
  kernel_size:
    tune_type: choice
    values: [3, 5]
  latent_dim:
    tune_type: choice
    values: [16, 32, 64]
  stride:
    tune_type: choice
    values: [1]
  padding:
    tune_type: choice
    values: ['same']
